//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxisBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxisBank_tblAllAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AxisBank_tblAllAccount()
        {
            this.AxisBank_tblBalance = new HashSet<AxisBank_tblBalance>();
        }
    
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IdCardType { get; set; }
        public string IdCardNumber { get; set; }
        public byte[] UploadPhoto { get; set; }
        public string Address { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AxisBank_tblBalance> AxisBank_tblBalance { get; set; }
    }
}
