//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxisBank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AxisBankDBEntities : DbContext
    {
        public AxisBankDBEntities()
            : base("name=AxisBankDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AxisBank_tblAllAccount> AxisBank_tblAllAccount { get; set; }
        public virtual DbSet<AxisBank_tblBalance> AxisBank_tblBalance { get; set; }
        public virtual DbSet<AxisBank_tblLogin> AxisBank_tblLogin { get; set; }
        public virtual DbSet<AxisBank_tblRole> AxisBank_tblRole { get; set; }
        public virtual DbSet<tblAccountStatement> tblAccountStatement { get; set; }
    }
}
